BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 1
  EPOCHS: 30
  LR: 1e-3
  local_ep: 3
  global_ep: 10
  MODEL_FILE_NAME: UBFC_UBFC_PURE_deepphys
  PLOT_LOSSES_AND_LR: False
  #datapath_list: ["/home/zhaobowen/tank/数据集/UBFC/UBFC2/","/home/zhaobowen/tank/数据集/MMPD/","/home/zhaobowen/tank/数据集/PURE/"]
  #dataset_list: ["UBFC-rPPG", "MMPD", "PURE"]
  #savepath_list: ["/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/train/","/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/train1/" ,"/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/train2/" ]
  datapath_list: [ "/home/zhaobowen/tank/数据集/UBFC/UBFC2/","/home/zhaobowen/tank/数据集/ECG-Fitness/视频版/","/home/zhaobowen/tank/数据集/PURE/" ]
  dataset_list: [ "UBFC-rPPG", "ECG-Fitness", "PURE" ]
  savepath_list: [ "/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/train/","/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/ECG_train/" ,"/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/train2/" ]

  num_users: 3
  DATA:
    INFO:
      LIGHT: [1, 2, 3]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
      MOTION: [1] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
      EXERCISE: [2] # 1 - True, 2 - False
      SKIN_COLOR: [3] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
      GENDER: [1, 2]  # 1 - Male, 2 - Female
      GLASSER: [1, 2] # 1 - True, 2 - False
      HAIR_COVER: [1, 2] # 1 - True, 2 - False
      MAKEUP: [1, 2] # 1 - True, 2 - False
    FS: 30
    test_list: "/home/zhaobowen/tank/数据集/ECG-Fitness/视频版/"
    test_savelist: "/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/ECG_train/"
    DATASET: UBFC-rPPG
    DO_PREPROCESS: False           # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/UBFC-rPPG/RawData"                     # Raw dataset path, need to be updated
    CACHED_PATH: "./save/rppg/train/"   # Processed dataset save path, need to be updated
    EXP_DATA_NAME: " "
    BEGIN: 0.0
    END: 0.8
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized','Standardized']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
VALID:
  DATA:
    INFO:
      LIGHT: [1, 2, 3]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
      MOTION: [1] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
      EXERCISE: [2] # 1 - True, 2 - False
      SKIN_COLOR: [3] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
      GENDER: [1, 2]  # 1 - Male, 2 - Female
      GLASSER: [1, 2] # 1 - True, 2 - False
      HAIR_COVER: [1, 2] # 1 - True, 2 - False
      MAKEUP: [1, 2] # 1 - True, 2 - False
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: False                # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/UBFC-rPPG/RawData"                     # Raw dataset path, need to be updated
    CACHED_PATH: "./save/rppg/valid/"
    #savepath_list: ["/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/val/","/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/val1/","/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/val2/"]# Processed dataset save path, need to be updated
    EXP_DATA_NAME: " "
    BEGIN: 0.8
    END: 1.0
    #valdataset_list: ["UBFC-rPPG", "MMPD", "PURE"]
    #valdatapath_list: ["/home/zhaobowen/tank/数据集/UBFC/UBFC2/","/home/zhaobowen/tank/数据集/MMPD/","/home/zhaobowen/tank/数据集/PURE/"]
    savepath_list: ["/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/val/","/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/ECG_val/","/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/val2/"]
    valdataset_list: [ "UBFC-rPPG", "ECG-Fitness", "PURE" ]
    valdatapath_list: [ "/home/zhaobowen/tank/数据集/UBFC/UBFC2/","/home/zhaobowen/tank/数据集/ECG-Fitness/视频版/","/home/zhaobowen/tank/数据集/PURE/" ]
    globaldatapath : "/home/zhaobowen/tank/数据集/UBFC-Phys_dataset/"
    globalsavepath : "/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/val3/"
    test_list: "/home/zhaobowen/tank/数据集/ECG-Fitness/视频版/"
    test_savelist: "/home/zhaobowen/user/save_data_zhaobowen/FedAvg_deephys/ECG_val/"
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR','MACC']
  USE_LAST_EPOCH: True                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/PURE/RawData"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/rppg_toolbox/PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: DeepPhys

INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH:   ""
